<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BonusesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $rows = DB::table('bonuses')->insertOrIgnore([
            0 =>
                [
                    'id' => 1,
                    'level' => 1,
                    'bonus' => '50.00',
                    'personal_deposit' => '200.00',
                    'team_turnover' => '1000.00',
                    'invitation_deposit' => '20.00',
                    'matching_bonus' => '0.00',
                    'leadership_bonus' => '0.00',
                    'is_invitation_deposit_available' => 0,
                    'is_regional_representative_status_available' => 0,
                    'affiliate_magnet' => 0,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            1 =>
                [
                    'id' => 2,
                    'level' => 2,
                    'bonus' => '75.00',
                    'personal_deposit' => '300.00',
                    'team_turnover' => '1500.00',
                    'invitation_deposit' => '40.00',
                    'matching_bonus' => '0.00',
                    'leadership_bonus' => '0.00',
                    'is_invitation_deposit_available' => 0,
                    'is_regional_representative_status_available' => 0,
                    'affiliate_magnet' => 0,
                    'fast_start' => 1,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            2 =>
                [
                    'id' => 3,
                    'level' => 3,
                    'bonus' => '110.00',
                    'personal_deposit' => '450.00',
                    'team_turnover' => '2750.00',
                    'invitation_deposit' => '60.00',
                    'matching_bonus' => '0.00',
                    'leadership_bonus' => '0.00',
                    'is_invitation_deposit_available' => 0,
                    'is_regional_representative_status_available' => 0,
                    'affiliate_magnet' => 0,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            3 =>
                [
                    'id' => 4,
                    'level' => 4,
                    'bonus' => '165.00',
                    'personal_deposit' => '675.00',
                    'team_turnover' => '4000.00',
                    'invitation_deposit' => '80.00',
                    'matching_bonus' => '0.00',
                    'leadership_bonus' => '0.00',
                    'is_invitation_deposit_available' => 0,
                    'is_regional_representative_status_available' => 0,
                    'affiliate_magnet' => 0,
                    'fast_start' => 1,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            4 =>
                [
                    'id' => 5,
                    'level' => 5,
                    'bonus' => '240.00',
                    'personal_deposit' => '1000.00',
                    'team_turnover' => '6000.00',
                    'invitation_deposit' => '100.00',
                    'matching_bonus' => '0.00',
                    'leadership_bonus' => '0.00',
                    'is_invitation_deposit_available' => 0,
                    'is_regional_representative_status_available' => 0,
                    'affiliate_magnet' => 0,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            5 =>
                [
                    'id' => 6,
                    'level' => 6,
                    'bonus' => '250.00',
                    'personal_deposit' => '1500.00',
                    'team_turnover' => '9000.00',
                    'invitation_deposit' => '120.00',
                    'matching_bonus' => '5.00',
                    'leadership_bonus' => '0.05',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 5,
                    'fast_start' => 1,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            6 =>
                [
                    'id' => 7,
                    'level' => 7,
                    'bonus' => '360.00',
                    'personal_deposit' => '1500.00',
                    'team_turnover' => '13500.00',
                    'invitation_deposit' => '140.00',
                    'matching_bonus' => '6.00',
                    'leadership_bonus' => '0.10',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 10,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            7 =>
                [
                    'id' => 8,
                    'level' => 8,
                    'bonus' => '540.00',
                    'personal_deposit' => '2750.00',
                    'team_turnover' => '20000.00',
                    'invitation_deposit' => '160.00',
                    'matching_bonus' => '7.00',
                    'leadership_bonus' => '0.20',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 15,
                    'fast_start' => 1,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            8 =>
                [
                    'id' => 9,
                    'level' => 9,
                    'bonus' => '810.00',
                    'personal_deposit' => '4000.00',
                    'team_turnover' => '30000.00',
                    'invitation_deposit' => '180.00',
                    'matching_bonus' => '8.00',
                    'leadership_bonus' => '0.30',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 20,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            9 =>
                [
                    'id' => 10,
                    'level' => 10,
                    'bonus' => '810.00',
                    'personal_deposit' => '4000.00',
                    'team_turnover' => '45000.00',
                    'invitation_deposit' => '200.00',
                    'matching_bonus' => '9.00',
                    'leadership_bonus' => '0.40',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 30,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            10 =>
                [
                    'id' => 11,
                    'level' => 11,
                    'bonus' => '1500.00',
                    'personal_deposit' => '6000.00',
                    'team_turnover' => '70000.00',
                    'invitation_deposit' => '220.00',
                    'matching_bonus' => '10.00',
                    'leadership_bonus' => '0.50',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 40,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            11 =>
                [
                    'id' => 12,
                    'level' => 12,
                    'bonus' => '2250.00',
                    'personal_deposit' => '9000.00',
                    'team_turnover' => '100000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '10.00',
                    'leadership_bonus' => '0.60',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => '2020-04-27 20:25:06',
                    'updated_at' => '2020-04-27 20:25:06',
                ],
            12 =>
                [
                    'id' => 13,
                    'level' => 13,
                    'bonus' => '3375.00',
                    'personal_deposit' => '12500.00',
                    'team_turnover' => '150000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '11.00',
                    'leadership_bonus' => '0.70',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            13 =>
                [
                    'id' => 14,
                    'level' => 14,
                    'bonus' => '5000.00',
                    'personal_deposit' => '17000.00',
                    'team_turnover' => '225000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '11.00',
                    'leadership_bonus' => '0.80',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            14 =>
                [
                    'id' => 15,
                    'level' => 15,
                    'bonus' => '7600.00',
                    'personal_deposit' => '25000.00',
                    'team_turnover' => '337500.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '12.00',
                    'leadership_bonus' => '0.90',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            15 =>
                [
                    'id' => 16,
                    'level' => 16,
                    'bonus' => '12000.00',
                    'personal_deposit' => '30000.00',
                    'team_turnover' => '500000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '12.00',
                    'leadership_bonus' => '1.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            16 =>
                [
                    'id' => 17,
                    'level' => 17,
                    'bonus' => '17000.00',
                    'personal_deposit' => '45000.00',
                    'team_turnover' => '750000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '12.00',
                    'leadership_bonus' => '1.20',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            17 =>
                [
                    'id' => 18,
                    'level' => 18,
                    'bonus' => '25500.00',
                    'personal_deposit' => '65000.00',
                    'team_turnover' => '1100000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '13.00',
                    'leadership_bonus' => '1.40',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            18 =>
                [
                    'id' => 19,
                    'level' => 19,
                    'bonus' => '38500.00',
                    'personal_deposit' => '95000.00',
                    'team_turnover' => '1700000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '13.00',
                    'leadership_bonus' => '1.60',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            19 =>
                [
                    'id' => 20,
                    'level' => 20,
                    'bonus' => '57500.00',
                    'personal_deposit' => '130000.00',
                    'team_turnover' => '2500000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '13.00',
                    'leadership_bonus' => '1.80',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            20 =>
                [
                    'id' => 21,
                    'level' => 21,
                    'bonus' => '86500.00',
                    'personal_deposit' => '185000.00',
                    'team_turnover' => '3750000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '14.00',
                    'leadership_bonus' => '2.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            21 =>
                [
                    'id' => 22,
                    'level' => 22,
                    'bonus' => '130000.00',
                    'personal_deposit' => '250000.00',
                    'team_turnover' => '5750000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '15.00',
                    'leadership_bonus' => '2.50',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            22 =>
                [
                    'id' => 23,
                    'level' => 23,
                    'bonus' => '195000.00',
                    'personal_deposit' => '350000.00',
                    'team_turnover' => '8500000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '16.00',
                    'leadership_bonus' => '3.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            23 =>
                [
                    'id' => 24,
                    'level' => 24,
                    'bonus' => '292000.00',
                    'personal_deposit' => '500000.00',
                    'team_turnover' => '12750000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '17.00',
                    'leadership_bonus' => '3.50',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            24 =>
                [
                    'id' => 25,
                    'level' => 25,
                    'bonus' => '438000.00',
                    'personal_deposit' => '700000.00',
                    'team_turnover' => '19500000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '18.00',
                    'leadership_bonus' => '4.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            25 =>
                [
                    'id' => 26,
                    'level' => 26,
                    'bonus' => '657000.00',
                    'personal_deposit' => '1000000.00',
                    'team_turnover' => '29000000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '19.00',
                    'leadership_bonus' => '4.50',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            26 =>
                [
                    'id' => 27,
                    'level' => 27,
                    'bonus' => '985000.00',
                    'personal_deposit' => '1400000.00',
                    'team_turnover' => '40000000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '20.00',
                    'leadership_bonus' => '5.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            27 =>
                [
                    'id' => 28,
                    'level' => 28,
                    'bonus' => '1478000.00',
                    'personal_deposit' => '1900000.00',
                    'team_turnover' => '65000000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '21.00',
                    'leadership_bonus' => '6.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            28 =>
                [
                    'id' => 29,
                    'level' => 29,
                    'bonus' => '2217000.00',
                    'personal_deposit' => '2750000.00',
                    'team_turnover' => '95000000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '23.00',
                    'leadership_bonus' => '7.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            29 =>
                [
                    'id' => 30,
                    'level' => 30,
                    'bonus' => '3325000.00',
                    'personal_deposit' => '4100000.00',
                    'team_turnover' => '125000000.00',
                    'invitation_deposit' => '240.00',
                    'matching_bonus' => '25.00',
                    'leadership_bonus' => '8.00',
                    'is_invitation_deposit_available' => 1,
                    'is_regional_representative_status_available' => 1,
                    'affiliate_magnet' => 50,
                    'fast_start' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
        ]);

        echo "Rows: $rows\n";
    }
}
