<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class MarketingPlansTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $rows = DB::table('marketing_plans')->insertOrIgnore([
            0 =>
                [
                    'id' => 1,
                    'name' => 'Start',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 20.0,
                    'max_invest_sum' => 249.0,
                    'min_duration' => 10,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 11,
                    'daily_percent' => 0.7,
                    'only_business_days' => 0,
                    'min_profit' => 10.5,
                    'max_profit' => 10.5,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            1 =>
                [
                    'id' => 2,
                    'name' => 'Profi',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 250.0,
                    'max_invest_sum' => 999.0,
                    'min_duration' => 30,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 31,
                    'daily_percent' => 0.8,
                    'only_business_days' => 0,
                    'min_profit' => 3.7,
                    'max_profit' => 3.7,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            2 =>
                [
                    'id' => 3,
                    'name' => 'Optimus',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 1000.0,
                    'max_invest_sum' => 4999.0,
                    'min_duration' => 60,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 61,
                    'daily_percent' => 0.9,
                    'only_business_days' => 0,
                    'min_profit' => 2.0,
                    'max_profit' => 2.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            3 =>
                [
                    'id' => 4,
                    'name' => 'President',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 5000.0,
                    'max_invest_sum' => 25000.0,
                    'min_duration' => 100,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 1.0,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            4 =>
                [
                    'id' => 5,
                    'name' => 'BTC',
                    'currency_type' => 'btc',
                    'min_invest_sum' => 0.01,
                    'max_invest_sum' => 10.0,
                    'min_duration' => 365,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.85,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            5 =>
                [
                    'id' => 6,
                    'name' => 'ETH',
                    'currency_type' => 'eth',
                    'min_invest_sum' => 0.1,
                    'max_invest_sum' => 250.0,
                    'min_duration' => 365,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.85,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            6 =>
                [
                    'id' => 7,
                    'name' => 'PZM',
                    'currency_type' => 'pzm',
                    'min_invest_sum' => 100.0,
                    'max_invest_sum' => 500000.0,
                    'min_duration' => 365,
                    'max_duration' => 365,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.8,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 10.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2019-11-30 12:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            7 =>
                [
                    'id' => 8,
                    'name' => 'Test BTC',
                    'currency_type' => 'btc',
                    'min_invest_sum' => 0.01,
                    'max_invest_sum' => 3.0,
                    'min_duration' => 0,
                    'max_duration' => 100,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.35,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '8.00',
                    'created_at' => null,
                    'updated_at' => '2019-11-30 08:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            8 =>
                [
                    'id' => 9,
                    'name' => 'Test ETH',
                    'currency_type' => 'eth',
                    'min_invest_sum' => 0.1,
                    'max_invest_sum' => 100.0,
                    'min_duration' => 0,
                    'max_duration' => 100,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.3,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '8.00',
                    'created_at' => null,
                    'updated_at' => '2019-11-30 08:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            9 =>
                [
                    'id' => 10,
                    'name' => 'Test PZM',
                    'currency_type' => 'pzm',
                    'min_invest_sum' => 100.0,
                    'max_invest_sum' => 250000.0,
                    'min_duration' => 0,
                    'max_duration' => 100,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.65,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '8.00',
                    'created_at' => null,
                    'updated_at' => '2019-11-30 08:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            10 =>
                [
                    'id' => 11,
                    'name' => 'Test USDT',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 500.0,
                    'max_invest_sum' => 2500.0,
                    'min_duration' => 0,
                    'max_duration' => 100,
                    'first_days_count_for_simple_percent' => 101,
                    'daily_percent' => 0.5,
                    'only_business_days' => 0,
                    'min_profit' => 1.4,
                    'max_profit' => 1.4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '8.00',
                    'created_at' => null,
                    'updated_at' => '2019-11-30 08:00:11',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            11 =>
                [
                    'id' => 12,
                    'name' => 'Standard 50$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 50.0,
                    'max_invest_sum' => 50.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.7,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            12 =>
                [
                    'id' => 13,
                    'name' => 'Standard 250$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 250.0,
                    'max_invest_sum' => 250.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.7,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            13 =>
                [
                    'id' => 14,
                    'name' => 'Standard 500$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 500.0,
                    'max_invest_sum' => 500.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.8,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            14 =>
                [
                    'id' => 15,
                    'name' => 'Standard 1000$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 1000.0,
                    'max_invest_sum' => 1000.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.8,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            15 =>
                [
                    'id' => 16,
                    'name' => 'Standard 2500$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 2500.0,
                    'max_invest_sum' => 2500.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.9,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            16 =>
                [
                    'id' => 17,
                    'name' => 'Standard 5000$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 5000.0,
                    'max_invest_sum' => 5000.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 1.0,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            17 =>
                [
                    'id' => 18,
                    'name' => 'Business',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 5000.0,
                    'max_invest_sum' => 500000.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 1.5,
                    'max_profit' => 5,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '12.50',
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 0,
                    'accrual_period' => 1,
                ],
            18 =>
                [
                    'id' => 19,
                    'name' => 'CryptoBusiness BTC',
                    'currency_type' => 'btc',
                    'min_invest_sum' => 0.05,
                    'max_invest_sum' => 10,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 2,
                    'max_profit' => 6,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '12.50',
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 7,
                ],
            19 =>
                [
                    'id' => 20,
                    'name' => 'CryptoBusiness ETH',
                    'currency_type' => 'eth',
                    'min_invest_sum' => 1,
                    'max_invest_sum' => 300,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 2,
                    'max_profit' => 6,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '12.50',
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 0,
                    'accrual_period' => 7,
                ],
            20 =>
                [
                    'id' => 21,
                    'name' => 'CryptoBusiness PZM',
                    'currency_type' => 'pzm',
                    'min_invest_sum' => 5000.00,
                    'max_invest_sum' => 10000000.00,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 2,
                    'max_profit' => 6,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => '12.50',
                    'created_at' => null,
                    'updated_at' => '2020-09-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 0,
                    'accrual_period' => 7,
                ],
            21 =>
                [
                    'id' => 22,
                    'name' => 'Mini',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 100.0,
                    'max_invest_sum' => 2000.0,
                    'min_duration' => 240,
                    'max_duration' => 240,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 0.5,
                    'max_profit' => 1,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-09-24 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            22 =>
                [
                    'id' => 23,
                    'name' => 'Standard 10000$',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 10000.0,
                    'max_invest_sum' => 10000.0,
                    'min_duration' => 200,
                    'max_duration' => 200,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 1.0,
                    'only_business_days' => 0,
                    'min_profit' => 0.0,
                    'max_profit' => 0.0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.01,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => null,
                    'updated_at' => '2020-12-20 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],
            23 =>
                [
                    'id' => 24,
                    'name' => 'Light',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 1000.0,
                    'max_invest_sum' => 5000.0,
                    'min_duration' => 800,
                    'max_duration' => 800,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 2,
                    'max_profit' => 4,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => 0,
                    'created_at' => null,
                    'updated_at' => '2020-12-29 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => 0,
                    'accrual_period' => 7,
                ],
            24 =>
                [
                    'id' => 25,
                    'name' => 'Invitation Deposit',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 100.0,
                    'max_invest_sum' => 100.0,
                    'min_duration' => 30,
                    'max_duration' => 30,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.72,
                    'only_business_days' => 0,
                    'min_profit' => 0,
                    'max_profit' => 0,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => 0,
                    'created_at' => null,
                    'updated_at' => '2020-01-08 00:00:00',
                    'deleted_at' => null,
                    'is_active' => 0,
                    'body_on' => null,
                    'accrual_period' => 1,
                ],

            25 =>
                [
                    'id' => 26,
                    'name' => 'Mini',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 100.0,
                    'max_invest_sum' => 2000.0,
                    'min_duration' => 300,
                    'max_duration' => 300,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 0.41,
                    'max_profit' => 0.8,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 0,
                    'withdrawal_commission' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 1,
                    'accrual_period' => 1,
                ],

            26 =>
                [
                    'id' => 27,
                    'name' => 'New Light',
                    'currency_type' => 'usd',
                    'min_invest_sum' => 20,
                    'max_invest_sum' => 5000.0,
                    'min_duration' => 800,
                    'max_duration' => 800,
                    'first_days_count_for_simple_percent' => 0,
                    'daily_percent' => 0.0,
                    'only_business_days' => 0,
                    'min_profit' => 0.67,
                    'max_profit' => 0.67,
                    'manual_percent' => null,
                    'min_withdrawal_request' => 0.0,
                    'coin_percent' => 0.0,
                    'available_for_withdrawal' => 1,
                    'withdrawal_commission' => 0,
                    'created_at' => Carbon::now(),
                    'updated_at' => null,
                    'deleted_at' => null,
                    'is_active' => 1,
                    'body_on' => 0,
                    'accrual_period' => 7,
                ],

        ]);

        echo "Rows: $rows\n";
    }
}
