<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TransactionTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $rows = DB::table('transaction_types')->insertOrIgnore([
            0 =>
                [
                    'id' => 1,
                    'name_ru' => 'Ввод средств',
                    'name_en' => 'Deposit',
                    'name_de' => 'Einzahlung',
                    'name_zh' => '存款',
                    'name_fr' => 'Dépôt',
                    'name_pl' => 'Depozyt',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            1 =>
                [
                    'id' => 2,
                    'name_ru' => 'Прибыль',
                    'name_en' => 'Profit',
                    'name_de' => 'Gewinn',
                    'name_zh' => '利潤',
                    'name_fr' => 'Le profit',
                    'name_pl' => 'Zysk',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            2 =>
                [
                    'id' => 3,
                    'name_ru' => 'Реферальные ур. 1',
                    'name_en' => 'Referral level 1',
                    'name_de' => 'Überweisungsebene 1',
                    'name_zh' => '推薦你。1',
                    'name_fr' => 'Référence ur. 1',
                    'name_pl' => 'Twój polecony 1',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            3 =>
                [
                    'id' => 4,
                    'name_ru' => 'Реферальные ур. 2',
                    'name_en' => 'Referral level 2',
                    'name_de' => 'Überweisungsebene 2',
                    'name_zh' => '推薦你。2',
                    'name_fr' => 'Référence ur. 2',
                    'name_pl' => 'Twój polecony 2',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            4 =>
                [
                    'id' => 5,
                    'name_ru' => 'Реферальные ур. 3',
                    'name_en' => 'Referral level 3',
                    'name_de' => 'Überweisungsebene 3',
                    'name_zh' => '推薦你。3',
                    'name_fr' => 'Référence ur. 3',
                    'name_pl' => 'Twój polecony 3',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            5 =>
                [
                    'id' => 6,
                    'name_ru' => 'Реферальные ур. 4',
                    'name_en' => 'Referral level 4',
                    'name_de' => 'Überweisungsebene 4',
                    'name_zh' => '推薦你。4',
                    'name_fr' => 'Référence ur. 4',
                    'name_pl' => 'Twój polecony 4',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            6 =>
                [
                    'id' => 7,
                    'name_ru' => 'Реферальные ур. 5',
                    'name_en' => 'Referral level 5',
                    'name_de' => 'Überweisungsebene 5',
                    'name_zh' => '推薦你。5',
                    'name_fr' => 'Référence ur. 5',
                    'name_pl' => 'Twój polecony 5',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            7 =>
                [
                    'id' => 8,
                    'name_ru' => 'Реферальные ур. 6',
                    'name_en' => 'Referral level 6',
                    'name_de' => 'Überweisungsebene 6',
                    'name_zh' => '推薦你。6',
                    'name_fr' => 'Référence ur. 6',
                    'name_pl' => 'Twój polecony 6',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            8 =>
                [
                    'id' => 9,
                    'name_ru' => 'Реферальные ур. 7',
                    'name_en' => 'Referral level 7',
                    'name_de' => 'Überweisungsebene 7',
                    'name_zh' => '推薦你。7',
                    'name_fr' => 'Référence ur. 7',
                    'name_pl' => 'Twój polecony 7',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            9 =>
                [
                    'id' => 10,
                    'name_ru' => 'Реферальные ур. 8',
                    'name_en' => 'Referral level 8',
                    'name_de' => 'Überweisungsebene 8',
                    'name_zh' => '推薦你。8',
                    'name_fr' => 'Référence ur. 8',
                    'name_pl' => 'Twój polecony 8',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            10 =>
                [
                    'id' => 11,
                    'name_ru' => 'Реферальные ур. 9',
                    'name_en' => 'Referral level 9',
                    'name_de' => 'Überweisungsebene 9',
                    'name_zh' => '推薦你。9',
                    'name_fr' => 'Référence ur. 9',
                    'name_pl' => 'Twój polecony 9',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            11 =>
                [
                    'id' => 12,
                    'name_ru' => 'Реферальные ур. 10',
                    'name_en' => 'Referral level 10',
                    'name_de' => 'Überweisungsebene 10',
                    'name_zh' => '推薦你。10',
                    'name_fr' => 'Référence ur. 10',
                    'name_pl' => 'Twój polecony 10',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            12 =>
                [
                    'id' => 13,
                    'name_ru' => 'Заявка на вывод',
                    'name_en' => 'Withdrawal request',
                    'name_de' => 'Auszahlungsantrag',
                    'name_zh' => '提款請求',
                    'name_fr' => 'Demande de retrait',
                    'name_pl' => 'Żądanie wypłaty',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            13 =>
                [
                    'id' => 14,
                    'name_ru' => 'Вывод',
                    'name_en' => 'Withdrawal',
                    'name_de' => 'Auszahlung',
                    'name_zh' => '結論',
                    'name_fr' => 'Conclusion',
                    'name_pl' => 'Wniosek',
                    'created_at' => '2019-04-13 00:00:38',
                    'updated_at' => '2019-04-13 00:00:38',
                    'deleted_at' => null,
                ],
            14 =>
                [
                    'id' => 15,
                    'name_ru' => 'Бонусы',
                    'name_en' => 'Bonuses',
                    'name_de' => 'Boni',
                    'name_zh' => '獎金',
                    'name_fr' => 'Les bonus',
                    'name_pl' => 'Bonusy',
                    'created_at' => '2019-05-24 07:24:00',
                    'updated_at' => '2019-05-24 07:24:00',
                    'deleted_at' => null,
                ],
            15 =>
                [
                    'id' => 16,
                    'name_ru' => 'Зарплата',
                    'name_en' => 'Salary',
                    'name_de' => 'Gehalt',
                    'name_zh' => '薪水',
                    'name_fr' => 'Le salaire',
                    'name_pl' => 'Wynagrodzenie',
                    'created_at' => '2019-06-26 11:34:00',
                    'updated_at' => '2019-06-26 11:34:00',
                    'deleted_at' => null,
                ],
            16 =>
                [
                    'id' => 17,
                    'name_ru' => 'Месячные бонусы',
                    'name_en' => 'Monthly bonuses',
                    'name_de' => 'Monatliche Prämien',
                    'name_zh' => '每月獎金',
                    'name_fr' => 'Bonus mensuels',
                    'name_pl' => 'Miesięczne bonusy',
                    'created_at' => '2019-06-27 03:00:00',
                    'updated_at' => '2019-06-27 03:00:00',
                    'deleted_at' => null,
                ],
            17 =>
                [
                    'id' => 18,
                    'name_ru' => 'Арбитражная торговля',
                    'name_en' => 'Arbitration Trading',
                    'name_de' => 'Schiedsgerichtsbarkeit',
                    'name_zh' => '仲裁交易',
                    'name_fr' => 'Trading d\'arbitrage',
                    'name_pl' => 'Handel arbitrażowy',
                    'created_at' => '2019-07-13 04:24:00',
                    'updated_at' => '2019-07-13 04:24:00',
                    'deleted_at' => null,
                ],
            18 =>
                [
                    'id' => 19,
                    'name_ru' => 'Покупка плана арбитражной торговли',
                    'name_en' => 'Buying an Arbitrage Trading Plan',
                    'name_de' => 'Kauf eines Arbitrage-Handelsplans',
                    'name_zh' => '購買套利交易計劃',
                    'name_fr' => 'Achat d`un plan de négociation d`arbitrage',
                    'name_pl' => 'Kupowanie planu handlowego na arbitraż',
                    'created_at' => '2019-07-13 07:00:00',
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            19 =>
                [
                    'id' => 20,
                    'name_ru' => 'Бонус при покупке арбитражного плана рефералом',
                    'name_en' => 'Referral bonus when buying an arbitration plan',
                    'name_de' => 'Empfehlungsbonus beim Kauf eines Schiedsgerichts',
                    'name_zh' => '購買仲裁計劃時的推薦獎金',
                    'name_fr' => 'Bonus de référence lors de l\'achat d\'un plan d\'arbitrage',
                    'name_pl' => 'Bonus za polecenie przy zakupie planu arbitrażowego',
                    'created_at' => '2019-08-07 23:48:00',
                    'updated_at' => '2019-08-07 23:48:00',
                    'deleted_at' => null,
                ],
            20 =>
                [
                    'id' => 21,
                    'name_ru' => 'Покупка плана системы мотивации',
                    'name_en' => 'Buying a Motivation System Plan',
                    'name_de' => 'Kauf eines Motivationsplans',
                    'name_zh' => '購買激勵系統計劃',
                    'name_fr' => 'Achat d\'un plan de système de motivation',
                    'name_pl' => 'Zakup planu systemu motywacyjnego',
                    'created_at' => '2019-08-14 15:22:00',
                    'updated_at' => '2019-08-14 15:22:00',
                    'deleted_at' => null,
                ],
            21 =>
                [
                    'id' => 22,
                    'name_ru' => 'Бонус к прибыли (мотивационная программа)',
                    'name_en' => 'Bonus to profit (motivation program)',
                    'name_de' => 'Bonus zum Profit (Motivationsprogramm)',
                    'name_zh' => '利潤獎勵（激勵計劃）',
                    'name_fr' => 'Bonus à gagner (programme de motivation)',
                    'name_pl' => 'Premia do zysku (program motywacyjny)',
                    'created_at' => '2019-09-04 21:18:00',
                    'updated_at' => '2019-09-04 21:18:00',
                    'deleted_at' => null,
                ],
            22 =>
                [
                    'id' => 23,
                    'name_ru' => 'Бонус к реферальным начислениям (мотивационная программа)',
                    'name_en' => 'Bonus to referral accruals (motivation program)',
                    'name_de' => 'Bonus auf Empfehlungsrückstellungen (Motivationsprogramm)',
                    'name_zh' => '轉介應計獎勵（激勵計劃）',
                    'name_fr' => 'Bonus pour les versements effectués (programme de motivation)',
                    'name_pl' => 'Premia do rozliczeń międzyokresowych (program motywacyjny)',
                    'created_at' => '2019-09-04 21:19:00',
                    'updated_at' => '2019-09-04 21:19:00',
                    'deleted_at' => null,
                ],
            23 =>
                [
                    'id' => 24,
                    'name_ru' => 'Перевод между аккаунтами',
                    'name_en' => 'Transfer between accounts',
                    'name_de' => 'Transfer zwischen Konten',
                    'name_zh' => '帳戶間轉帳',
                    'name_fr' => 'Virement entre comptes',
                    'name_pl' => 'Transfer między kontami',
                    'created_at' => '2019-09-05 12:00:00',
                    'updated_at' => '2019-09-05 12:00:00',
                    'deleted_at' => null,
                ],
            24 =>
                [
                    'id' => 25,
                    'name_ru' => 'Перевод криптокошельков',
                    'name_en' => 'Перевод криптокошельков',
                    'name_de' => 'Перевод криптокошельков',
                    'name_zh' => 'Перевод криптокошельков',
                    'name_fr' => 'Перевод криптокошельков',
                    'name_pl' => 'Перевод криптокошельков',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            25 =>
                [
                    'id' => 26,
                    'name_ru' => 'Прибыль в криптовалюте',
                    'name_en' => 'Прибыль в криптовалюте',
                    'name_de' => 'Прибыль в криптовалюте',
                    'name_zh' => 'Прибыль в криптовалюте',
                    'name_fr' => 'Прибыль в криптовалюте',
                    'name_pl' => 'Прибыль в криптовалюте',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            26 =>
                [
                    'id' => 27,
                    'name_ru' => 'Инвестиции в маркетплейс',
                    'name_en' => 'Инвестиции в маркетплейс',
                    'name_de' => 'Инвестиции в маркетплейс',
                    'name_zh' => 'Инвестиции в маркетплейс',
                    'name_fr' => 'Инвестиции в маркетплейс',
                    'name_pl' => 'Инвестиции в маркетплейс',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            27 =>
                [
                    'id' => 28,
                    'name_ru' => 'Продажа доли маркетплейса',
                    'name_en' => 'Продажа доли маркетплейса',
                    'name_de' => 'Продажа доли маркетплейса',
                    'name_zh' => 'Продажа доли маркетплейса',
                    'name_fr' => 'Продажа доли маркетплейса',
                    'name_pl' => 'Продажа доли маркетплейса',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            28 =>
                [
                    'id' => 29,
                    'name_ru' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'name_en' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'name_de' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'name_zh' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'name_fr' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'name_pl' => 'id типа транзкции "Инвестиции в маркетинг с основного баланса"',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            29 =>
                [
                    'id' => 30,
                    'name_ru' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'name_en' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'name_de' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'name_zh' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'name_fr' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'name_pl' => 'id типа транзкции "Инвестиции в маркетинг с баланса коина"',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            30 =>
                [
                    'id' => 31,
                    'name_ru' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'name_en' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'name_de' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'name_zh' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'name_fr' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'name_pl' => 'Перевод прибыли с маркетингового плана на основной счет',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            31 =>
                [
                    'id' => 32,
                    'name_ru' => 'Прибыль от партнерской программы',
                    'name_en' => 'Прибыль от партнерской программы',
                    'name_de' => 'Прибыль от партнерской программы',
                    'name_zh' => 'Прибыль от партнерской программы',
                    'name_fr' => 'Прибыль от партнерской программы',
                    'name_pl' => 'Прибыль от партнерской программы',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            32 =>
                [
                    'id' => 33,
                    'name_ru' => 'Перевод тела с маркетингового плана на основной счет',
                    'name_en' => 'Перевод тела с маркетингового плана на основной счет',
                    'name_de' => 'Перевод тела с маркетингового плана на основной счет',
                    'name_zh' => 'Перевод тела с маркетингового плана на основной счет',
                    'name_fr' => 'Перевод тела с маркетингового плана на основной счет',
                    'name_pl' => 'Перевод тела с маркетингового плана на основной счет',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            33 =>
                [
                    'id' => 34,
                    'name_ru' => 'Депозитный процент',
                    'name_en' => 'Deposit procent',
                    'name_de' => 'Einzahlungsprozent',
                    'name_zh' => '存款保证金',
                    'name_fr' => 'Pourcentage de dépôt',
                    'name_pl' => 'Procent depozytu',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            34 =>
                [
                    'id' => 35,
                    'name_ru' => 'Начислено через админ',
                    'name_en' => 'Accrued through admin',
                    'name_de' => 'Durch Admin entstanden',
                    'name_zh' => '通过管理员产生',
                    'name_fr' => 'Accru via admin',
                    'name_pl' => 'Naliczone przez administratora',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            35 =>
                [
                    'id' => 36,
                    'name_ru' => 'Запрос на ввод монетой',
                    'name_en' => 'Request deposit coin',
                    'name_de' => 'Request deposit coin',
                    'name_zh' => 'Request deposit coin',
                    'name_fr' => 'Request deposit coin',
                    'name_pl' => 'Request deposit coin',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            36 =>
                [
                    'id' => 37,
                    'name_ru' => 'Ввод монетой',
                    'name_en' => 'Deposit coin',
                    'name_de' => 'Deposit coin',
                    'name_zh' => 'Deposit coin',
                    'name_fr' => 'Deposit coin',
                    'name_pl' => 'Deposit coin',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            37 =>
                [
                    'id' => 38,
                    'name_ru' => 'Матчинг бонус',
                    'name_en' => 'Matching Bonus',
                    'name_de' => 'Matching Bonus',
                    'name_zh' => 'Matching Bonus',
                    'name_fr' => 'Matching Bonus',
                    'name_pl' => 'Matching Bonus',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            38 =>
                [
                    'id' => 39,
                    'name_ru' => 'Пополнение игрового баланаса',
                    'name_en' => 'Game balance top up',
                    'name_de' => 'Game balance top up',
                    'name_zh' => 'Game balance top up',
                    'name_fr' => 'Game balance top up',
                    'name_pl' => 'Game balance top up',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            39 =>
                [
                    'id' => 42,
                    'name_ru' => 'Система',
                    'name_en' => 'System',
                    'name_de' => 'System',
                    'name_zh' => 'System',
                    'name_fr' => 'System',
                    'name_pl' => 'System',
                    'created_at' => null,
                    'updated_at' => null,
                    'deleted_at' => null,
                ],
            40 =>
                [
                    'id' => 43,
                    'name_ru' => 'Покупка услуг',
                    'name_en' => 'Buy services',
                    'name_de' => 'Kauf von Dienstleistungen',
                    'name_zh' => 'Buy services',
                    'name_fr' => 'Achat de services',
                    'name_pl' => 'Zakup usług',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            41 =>
                [
                    'id' => 44,
                    'name_ru' => 'Бонус от реферрала за покупку услуги',
                    'name_en' => 'Referral bonus for purchasing a service',
                    'name_de' => 'Empfehlungsbonus für den Kauf einer Dienstleistung',
                    'name_zh' => 'Referral bonus for purchasing a service',
                    'name_fr' => 'Referral bonus for purchasing a service',
                    'name_pl' => 'Referral bonus for purchasing a service',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            42 =>
                [
                    'id' => 45,
                    'name_ru' => 'Оборот первого уровня за покупку услуги',
                    'name_en' => 'First level turnover for purchasing a service',
                    'name_de' => 'First level turnover for purchasing a service',
                    'name_zh' => 'First level turnover for purchasing a service',
                    'name_fr' => 'First level turnover for purchasing a service',
                    'name_pl' => 'First level turnover for purchasing a service',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            43 =>
                [
                    'id' => 46,
                    'name_ru' => 'Оборот команды за покупку услуги',
                    'name_en' => 'Team turnover for purchasing a service',
                    'name_de' => 'Team turnover for purchasing a service',
                    'name_zh' => 'Team turnover for purchasing a service',
                    'name_fr' => 'Team turnover for purchasing a service',
                    'name_pl' => 'Team turnover for purchasing a service',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            44 =>
                [
                    'id' => \App\Models\Consts\TransactionsTypesConsts::USER_STATUS_REGIONAL_REPRESENTATIVE,
                    'name_ru' => 'Оплата статуса "Региональный представитель"',
                    'name_en' => 'Payment for the "Regional Representative" status',
                    'name_de' => 'Payment for the "Regional Representative" status',
                    'name_zh' => 'Payment for the "Regional Representative" status',
                    'name_fr' => 'Payment for the "Regional Representative" status',
                    'name_pl' => 'Payment for the "Regional Representative" status',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            45 =>
                [
                    'id' => \App\Models\Consts\TransactionsTypesConsts::USER_STATUS_REGIONAL_REPRESENTATIVE_REJECTED,
                    'name_ru' => 'Возврат средств за заявку на статус "Региональный представитель" при отказе',
                    'name_en' => 'Refunds for an application for the "Regional Representative" status in case of refusal',
                    'name_de' => 'Refunds for an application for the "Regional Representative" status in case of refusal',
                    'name_zh' => 'Refunds for an application for the "Regional Representative" status in case of refusal',
                    'name_fr' => 'Refunds for an application for the "Regional Representative" status in case of refusal',
                    'name_pl' => 'Refunds for an application for the "Regional Representative" status in case of refusal',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            46 =>
                [
                    'id' => \App\Models\Consts\TransactionsTypesConsts::LEADERSHIP_BONUS,
                    'name_ru' => 'Лидерский бонус',
                    'name_en' => 'Leadership bonus',
                    'name_de' => 'Leadership bonus',
                    'name_zh' => 'Leadership bonus',
                    'name_fr' => 'Leadership bonus',
                    'name_pl' => 'Leadership bonus',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            47 =>
                [
                    'id' => 50,
                    'name_ru' => 'Валютообмен',
                    'name_en' => 'Exchange',
                    'name_de' => 'Exchange',
                    'name_zh' => 'Exchange',
                    'name_fr' => 'Exchange',
                    'name_pl' => 'Exchange',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            49 => [
                'id' => 52,
                'name_ru' => 'Отправка денежного перевода',
                'name_en' => 'Sending money transfer',
                'name_de' => 'Sending money transfer',
                'name_zh' => 'Sending money transfer',
                'name_fr' => 'Sending money transfer',
                'name_pl' => 'Sending money transfer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            50 => [
                'id' => 53,
                'name_ru' => 'Получение денежного перевода',
                'name_de' => 'Receiving money transfer',
                'name_en' => 'Receiving money transfer',
                'name_zh' => 'Receiving money transfer',
                'name_fr' => 'Receiving money transfer',
                'name_pl' => 'Receiving money transfer',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            51 => [
                'id' => 54,
                'name_ru' => 'Покупка места на карте партнёров (30 дней)',
                'name_de' => 'Buying a place on the partners\' map (30 days)',
                'name_en' => 'Buying a place on the partners\' map (30 days)',
                'name_zh' => 'Buying a place on the partners\' map (30 days)',
                'name_fr' => 'Buying a place on the partners\' map (30 days)',
                'name_pl' => 'Buying a place on the partners\' map (30 days)',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            52 => [
                'id' => 55,
                'name_ru' => 'Возврат денег за размещение на карте партнеров',
                'name_de' => 'Refund for placement on partners\' map',
                'name_en' => 'Refund for placement on partners\' map',
                'name_zh' => 'Refund for placement on partners\' map',
                'name_fr' => 'Refund for placement on partners\' map',
                'name_pl' => 'Refund for placement on partners\' map',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
            53 => [
                'id' => 56,
                'name_ru' => 'Возврат незачисленных 2% по линейной партнерской программе',
                'name_de' => 'Refund of not credited 2% under the linear affiliate program',
                'name_en' => 'Refund of not credited 2% under the linear affiliate program',
                'name_zh' => 'Refund of not credited 2% under the linear affiliate program',
                'name_fr' => 'Refund of not credited 2% under the linear affiliate program',
                'name_pl' => 'Refund of not credited 2% under the linear affiliate program',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'deleted_at' => null,
            ],
           
            54 =>
                [
                    'id' => \App\Models\Consts\TransactionsTypesConsts::INVITE_RESET_DEPOSIT,
                    'name_ru' => 'Отмена инвайта',
                    'name_en' => 'Cancel invite',
                    'name_de' => 'Cancel invite',
                    'name_zh' => 'Cancel invite',
                    'name_fr' => 'Cancel invite',
                    'name_pl' => 'Cancel invite',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],

            55 =>
                [
                    'id' => \App\Models\Consts\TransactionsTypesConsts::INVITE_REF_DEPOSIT,
                    'name_ru' => 'Отправка инвайта',
                    'name_en' => 'Sending an invite',
                    'name_de' => 'Sending an invite',
                    'name_zh' => 'Sending an invite',
                    'name_fr' => 'Sending an invite',
                    'name_pl' => 'Sending an invite',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                ],
            56 => [
                'id' => \App\Models\Consts\TransactionsTypesConsts::DINWAY_WALLET_DEBT_USD_WITHDRAWAL,
                    'name_ru' => 'Вывод денег из Dinway Wallet (debt_usd)',
                    'name_en' => 'Withdrawing money from Dinway Wallet (debt_usd)',
                    'name_de' => 'Withdrawing money from Dinway Wallet (debt_usd)',
                    'name_zh' => 'Withdrawing money from Dinway Wallet (debt_usd)',
                    'name_fr' => 'Withdrawing money from Dinway Wallet (debt_usd)',
                    'name_pl' => 'Withdrawing money from Dinway Wallet (debt_usd)',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
            ]
        ]);

        echo "Rows: $rows\n";
    }
}
