<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class BonusesTabelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('bonuses')->insert([
            [
                'id'         	     => 1,
                'level'    		     => 1,
                'bonus'    		     => 50,
                'personal_deposit'   => 200,
                'team_turnover'      => 1000,
                'invitation_deposit' => 20,
                'matching_bonus'     => 0,
                'affiliate_magnet'   => 0,
                'fast_start'         => 0,
                'created_at' 	     => Carbon::now(),
                'updated_at' 	     => Carbon::now(),
            ],
            [
                'id'                 => 2,
                'level'              => 2,
                'bonus'              => 75,
                'personal_deposit'   => 300,
                'team_turnover'      => 1500,
                'invitation_deposit' => 40,
                'matching_bonus'     => 0,
                'affiliate_magnet'   => 0,
                'fast_start'         => 1,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 3,
                'level'              => 3,
                'bonus'              => 110,
                'personal_deposit'   => 450,
                'team_turnover'      => 2750,
                'invitation_deposit' => 60,
                'matching_bonus'     => 0,
                'affiliate_magnet'   => 0,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 4,
                'level'              => 4,
                'bonus'              => 165,
                'personal_deposit'   => 675,
                'team_turnover'      => 4000,
                'invitation_deposit' => 80,
                'matching_bonus'     => 0,
                'affiliate_magnet'   => 0,
                'fast_start'         => 1,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 5,
                'level'              => 5,
                'bonus'              => 240,
                'personal_deposit'   => 1000,
                'team_turnover'      => 6000,
                'invitation_deposit' => 100,
                'matching_bonus'     => 0,
                'affiliate_magnet'   => 0,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 6,
                'level'              => 6,
                'bonus'              => 250,
                'personal_deposit'   => 1500,
                'team_turnover'      => 5000,
                'invitation_deposit' => 120,
                'matching_bonus'     => 5,
                'affiliate_magnet'   => 5,
                'fast_start'         => 1,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 7,
                'level'              => 7,
                'bonus'              => 360,
                'personal_deposit'   => 1500,
                'team_turnover'      => 13500,
                'invitation_deposit' => 140,
                'matching_bonus'     => 6,
                'affiliate_magnet'   => 10,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 8,
                'level'              => 8,
                'bonus'              => 540,
                'personal_deposit'   => 2750,
                'team_turnover'      => 20000,
                'invitation_deposit' => 160,
                'matching_bonus'     => 7,
                'affiliate_magnet'   => 15,
                'fast_start'         => 1,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 9,
                'level'              => 9,
                'bonus'              => 810,
                'personal_deposit'   => 4000,
                'team_turnover'      => 30000,
                'invitation_deposit' => 180,
                'matching_bonus'     => 8,
                'affiliate_magnet'   => 20,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 10,
                'level'              => 10,
                'bonus'              => 810,
                'personal_deposit'   => 4000,
                'team_turnover'      => 45000,
                'invitation_deposit' => 200,
                'matching_bonus'     => 9,
                'affiliate_magnet'   => 30,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 11,
                'level'              => 11,
                'bonus'              => 1215,
                'personal_deposit'   => 6000,
                'team_turnover'      => 67000,
                'invitation_deposit' => 220,
                'matching_bonus'     => 10,
                'affiliate_magnet'   => 40,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            [
                'id'                 => 12,
                'level'              => 12,
                'bonus'              => 1810,
                'personal_deposit'   => 9000,
                'team_turnover'      => 100000,
                'invitation_deposit' => 240,
                'matching_bonus'     => 11,
                'affiliate_magnet'   => 50,
                'fast_start'         => 0,
                'created_at'         => Carbon::now(),
                'updated_at'         => Carbon::now(),
            ],
            
        ]);
    }
}
